### ISSUE TITLE
1.3.2 doesn't show my monitors anymore

### ISSUE THREAD

**Issue by e30Birdy** [bitgapp/Cursr#11]
https://imgur.com/a/f5rRoXG

So i just upgraded to 1.3.2 on Windows 10 and now it isnt showing my monitors anymore to select where i want them attached. Also the upgrading from the app has never worked for me. I manually have to go to the webpage and download the new version.

I also uninstalled completely and reinstalled and rebooted with no change. 1.3.1 worked fine before.

**Comment by e30Birdy** [comment]
Just reinstalled 1.3.1 and setup is back to working fine again with both my panels showing up.

**Comment by ragauskl** [comment]
Could I ask you to send me 2 log files located in 'C:\Users\\<user>\AppData\Roaming\cursr\Logs', they may contain some additional information on what's happening. You can add them here or send me over email contact@cursr.app 

Issue is likely due to the fact that I've switched to native Windows APIs instead of depending on 3rd party library to get information about displays as it was returning invalid information in list of other cases, I tested on 2 Windows 10 systems and it worked, but there might be something different on yours, if I won't find anything unusual in logs, in upcoming days I'll release v 1.3.3 with improved logging and ask you to send the log files again after trying to update and running the application

**Comment by e30Birdy** [comment]
> Could I ask you to send me 2 log files located in 'C:\Users\<user>\AppData\Roaming\cursr\Logs', they may contain some additional information on what's happening. You can add them here or send me over email [contact@cursr.app](mailto:contact@cursr.app)
> 
> Issue is likely due to the fact that I've switched to native Windows APIs instead of depending on 3rd party library to get information about displays as it was returning invalid information in list of other cases, I tested on 2 Windows 10 systems and it worked, but there might be something different on yours, if I won't find anything unusual in logs, in upcoming days I'll release v 1.3.3 with improved logging and ask you to send the log files again after trying to update and running the application

For sure. Gimme a little and I will send

**Comment by e30Birdy** [comment]
Both log files are empty. What is funny though is it also doesn't open the app window as of 1.3.2. It opens in taskbar but in previous versions it actually opens the screen to show the monitors and their connection like it did previously.

**Comment by ragauskl** [comment]
Ahh fun fun fun :D fix one issue and then 5 arise 

Okay I'll look into that as well, will release next version with increased logging, that should definitely populate the logs , will let you know as soon as it's out

**Comment by e30Birdy** [comment]
> Ahh fun fun fun :D fix one issue and then 5 arise
> 
> Okay I'll look into that as well, will release next version with increased logging, that should definitely populate the logs , will let you know as soon as it's out, maybe even today

That would be great

**Comment by ragauskl** [comment]
I've made custom build [download](https://drive.google.com/file/d/1cj28Jw3eveiMlLL-OCO0yms5gPR_0-kT/view?usp=sharing) for debugging , could you run installer  (no need to uninstall previous cursr version) and try to launch app then?

Log files should now have something in them, and there will be new file 'native.log'.

I've added small change which unlikely, but might fix the issue, if it by any chance did fix it, could I still ask you to send me 'native.log' so I can better understand the context in which issue happened?

**Comment by e30Birdy** [comment]
I sent you an email with the log. The "small" change actually did fix the issue here.

**Comment by ragauskl** [comment]
Perfect, thank you

In terms of the app update not working, what exactly happens?
Does it show notification that update has been downloaded and asks you to  restart the app?
Does the app not start after the restart?
