### ISSUE TITLE
THANK YOU FOR CREATING THIS APP

### ISSUE THREAD

**Issue by ms3056** [bitgapp/Cursr#12]
### Description
Thank you - so VERY VERY MUCH - for creating this app. I was using DisplayFusion for this capability only - which is a waste for softwar with so many functions - that I didn't need. 

This app is so useful - if ANYONE with multiple monitors is not using this app - it is simple - they just don't know they need it. 

Thank you!

**Comment by ragauskl** [comment]
@ms3056 Thank you, I'm really glad you found it useful 😁 Your words made my day, it definitely helps with motivation knowing that this is useful to people as I'm putting all my time in it. 

It's still far from complete and there will be more features and improvements coming in future, there's new release (1.4.0) coming out this month with new features, then I'll work on improving existing issues/performance and then more new features including KVM.

If you have any requests or/and would like to see specific improvements or features in Cursr, feel free to let me know and I'll see what and when I can do/add to Cursr
