### ISSUE TITLE
Mouse transitions don't work on Fedora 34 Gnome 40

### ISSUE THREAD

**Issue by airtonix** [bitgapp/Cursr#15]
### Describe the Bug/Issue

Setup a transition from external monitors to laptop screen, but mouse is still stuck.

### Steps to Reproduce

1. Go to https://github.com/bitgapp/Cursr/releases/tag/v1.4.1
2. download the appimage
3. mark the appimage as executable
4. run the appimage
5. see the cursr icon show up in the top icons (you need to have installed some kind of top icons gnome shell extension)
6. Click on the cursr icon
7. select Open

![image](https://user-images.githubusercontent.com/61225/148460748-9e7fb646-889b-41ca-ae86-c8c223ebb811.png)

my screens: 

![image](https://user-images.githubusercontent.com/61225/148460813-8e03b382-8d24-4138-adf2-2808ae789b2b.png)
![image](https://user-images.githubusercontent.com/61225/148460826-cd46e2de-053f-45a6-b871-ddbfdf7942a8.png)
![image](https://user-images.githubusercontent.com/61225/148460844-944c39a7-e403-43b9-b307-c3abf38697a2.png)

```
~ 
> inxi --system --graphics
System:    Host: pennyroyal Kernel: 5.15.11-100.fc34.x86_64 x86_64 bits: 64 Desktop: GNOME 40.7
           Distro: Fedora release 34 (Thirty Four)
Graphics:  Device-1: Intel HD Graphics 630 driver: i915 v: kernel
           Device-2: NVIDIA GP107M [GeForce GTX 1050 Mobile] driver: nvidia v: 495.46
           Device-3: Sunplus Innovation Integrated_Webcam_HD type: USB driver: uvcvideo
           Display: wayland server: X.Org 1.21.1.3 driver: loaded: modesetting,nvidia
           unloaded: fbdev,nouveau,vesa resolution: 1: 1920x1080~60Hz 2: 3440x1440~60Hz 3: 3440x1440~60Hz
           OpenGL: renderer: Mesa Intel HD Graphics 630 (KBL GT2) v: 4.6 Mesa 21.1.8
```

### Expected Behavior

**Screenshots**

### Your Environment

```
OS: Fedora release 34 (Thirty Four) x86_64 
Kernel: 5.15.11-100.fc34.x86_64 
Resolution: 3440x1440 
DE: GNOME 40.7 
WM: Mutter 
Cursr: https://github.com/bitgapp/Cursr/releases/tag/v1.4.1
```

**Comment by ragauskl** [comment]
@airtonix Could I ask you to download latest version 1.4.2, when you open the application make sure you enable Cursr as it seems to be disabled in the image you attached

Disabled state is indicated by darkened colour borders and by button (amber colour if disabled) in bottom right corner 

![image](https://user-images.githubusercontent.com/9280160/150630701-bb2c7d07-af36-40a1-8306-7b229eeccfd2.png)


Cursr is enabled by default, it can be toggled on and off by clicking on mentioned button above or by using keyboard shortcut 'Shift + Alt + D' (Shortcut can be changed at any time from settings - middle button bottom right corner)

**Comment by airtonix** [comment]
Oh 

None of that was obvious when using the UI.

Perhaps a UX review would be helpful

**Comment by ragauskl** [comment]
Well there's two visual indicators that something is wrong
* Paired borders are greyed out/darkened
* Button to disable/enable Cursr has amber colour indicating 'warning' and if you hover it tooltip explains that Cursr transitions are disabled

But I can see how none of that can be obvious if one disables Cursr by accidentally using keyboard shortcut before seeing app in enabled mode, which in most cases shouldn't happen, but can
