### ISSUE TITLE
Full screen games mess up on screen edge

### ISSUE THREAD

**Issue by Manwurgelzel** [bitgapp/Cursr#16]
When playing full screen games, such as League of Legends, Cursr will cause the mouse to jump all over the place when placed on the edge of the screen next to the second monitor.

**Comment by ragauskl** [comment]
@Manwurgelzel Yeah, I've experienced same issue when using vertical or horizontal loop on single screen and playing a full-screen game

### Current Solution
Disable Cursr while playing full-screen games, you can do that by using keyboard shortcut `Shift+Alt+D` (set by default, you can always change this in `Settings > Keyboard Shortcuts`), it will enable and disable mouse transitions by Cursr

### Reason for the issue

Cursr works as it should technically, but in games it depends on how the game tracks/traps the mouse, some keep mouse in cantered (in which case Cursr won't cause issues) but some don't which then causes issues as Cursr does it's work

### Future solution

It is an annoying issue, but so far I didn't find a good enough solution, but some of options are:
* If a game is detected in full-screen mode - disable Cursr transitions for that display (if mouse can still escape to other screens - then transitions will still work on them)
* Allow to add a list of apps to Cursr so it auto-disables when they are running in full-screen mode

If anyone has better ideas, I'm always open to suggestions

Unfortunately I won't probably be able to get to this issue in nearest few months as I'm working alone on this and there's list of other higher priority issues/tasks, where's this is more of an enhancement for user experience as there's a rather easy workaround of using keyboard shortcut to temporary disable/enable Cursr

**Comment by ragauskl** [comment]
@Manwurgelzel Okay seems like I was wrong/misunderstood the issue described.

From my experience I was having issues with games where cursor controls camera, as when cursor crosses over a link in-game camera calculations mess up as they don't expect the cursor to do that

But I still downloaded League of Legends to check out the problem and it seems like it's a different issue:
* I didn't get cursor jumping all over the place, my guess this is related to another issue which I've fixed for v1.4.2, which would explain why I was not seeing the issue that you described. So with v1.4.2 that might be fixed
* However there's another issue where if  right click on map, in game click happens elsewhere, to the far top and left of the actual cursor, even if Cursr is doing nothing/is disabled which leads me to think it's a problem of Cursr monitoring system events

So I'll see what I can do about it as soon as I can

**Comment by Manwurgelzel** [comment]
Ok sounds good
