### ISSUE TITLE
Mouse Transition Unexpectedly Unidirectional 

### ISSUE THREAD

**Issue by deathernater** [bitgapp/Cursr#17]
### Describe the Bug/Issue
I could only go left to right but not right to left with my screen configuration. Please reference attached video for more information:
https://discord.com/channels/886961548105515068/886961548105515071/932078548116725760

### Expected Behavior
I would expect bi-directional transitions being able to go from one screen edge to another back & forth. I am referring to the yellow colored transition zone in the linked video of the issue.

### Your Environment
 - OS Details: Windows 10 x64 [Latest Updates 01/15/2022]
 - Cursr Version: 1.4.2 prerelease

**Comment by ragauskl** [comment]
Closing issue, fixed with release v1.4.2
