### ISSUE TITLE
I want a 3rd edge (at least in one direction)

### ISSUE THREAD

**Issue by ltd** [bitgapp/Cursr#2]
### Describe the Issue
Love the app,  I find myself hitting the wall on one edge that I wish I could join an existing pairing.  I know it really complicates things because I'm not sure if expected cursor movement in both directions would be the same. 
### Additional context
<img width="622" alt="Cursor_and_Cursr" src="https://user-images.githubusercontent.com/67152/124957838-806d0580-dfe7-11eb-8845-a5e20b16906c.png">

**Comment by ragauskl** [comment]
Something similar could be achieved when custom ratio border linking will be available, as right now it's just 1:1. There's still is list of tasks before that but it will be coming out this summer likely. With that you could do something like this:

![image](https://user-images.githubusercontent.com/9280160/125081310-87bb0e80-e0ce-11eb-84ae-e4d7dc9878d1.png)

Alternatively a feature could be added where additional borders can be added to existing pairing. 

![image](https://user-images.githubusercontent.com/9280160/125083444-13359f00-e0d1-11eb-9219-21882a4184dd.png)


However one border can only transition to one other border in same linked group, so:
* moving mouse past screen A bottom to top of screen B
* and moving mouse past screen A left border to top of screen B can be achieved without a problem
* but if you move from top of screen B, you can only choose one of A borders to move to, I would guess bottom of screen A in this case.

I was thinking of adding that at some point, could fit it in this summer with the custom ratio link feature.

Does the above describe functionality that you would like? If not could you describe your thoughts in more detail?

**Comment by ltd** [comment]
ratio board linking is what i want, thanks

**Comment by ragauskl** [comment]
@ltd v1.4.0 with mentioned functionality is now live, it is a paid feature however (as have been mention in https://cursr.app since initial release of Cursr)

Cursr has a free time limited trial mode to try out paid features
