### ISSUE TITLE
Detect when dragging a window with the mouse

### ISSUE THREAD

**Issue by robmonte** [bitgapp/Cursr#20]
### Describe the Issue
I'm not sure if this is possible depending on each OS, but it would be helpful if Cursr could know when you're dragging a window versus just moving the mouse by itself. The reason for this is that if you are utilizing a feature like Window Snap in Windows 10/11, or have a program like Rectangle installed on MacOS, Cursr can provide a "padding" on the edge of the screen to let you resize the windows. The padding stops the mouse from moving into the next monitor immediately so that you can release the mouse button for the window resize action.

If the user continues to move the mouse into the padding, then it moves the window into the next monitor instead as expected. Of course, this setting should be controlled by a toggle for those that don't want it.

**Comment by ragauskl** [comment]
Yeah, I believe it can be detected, that is an annoying issue and also when not dragging - but trying to hit a button or program icon on the edge it's easy to overshoot especially when not being used to Cursr. I had it in my list for a while now just didn't find time to get to it but I will be definitely addressing both of the issues, most likely this year with the release of KVM feature

**Comment by ragauskl** [comment]
@Savant-sys I've finally released Cursr 1.5.0 as a stable release and will be looking into this feature for next update

**Comment by ragauskl** [comment]
@robmonte  With v1.6.0 release Cursr now has 2 options that help to deal with the issue where borders are linked by Cursr (borders joined natively by OS will not be affected):
* A keyboard shortcut which you can set in settings. Once set key(s) are pressed and held Cursr will allow (if by default disabled) or disallow (if by default enabled) mouse transitions through custom links. So you could set it to 'Alt' and when dragging a window, if you want to snap it to edge, hold Alt and mouse won't move over custom Cursr borders
*  Set mouse speed in settings, if mouse is moved at set speed or lower it will not move over custom Cursr borders. So when dragging a window, if you drag it quickly - you can move it to another display, but if you move it slowly bellow the threshold it will stay within the same display and allow you to snap it to the edge. This also allows to move slowly to border and if you change your mind or did not move the mouse fast enough you can 'push through' the border if you move the mouse at faster speed
