### ISSUE TITLE
Mouse jumps around when exiting VM Ware capture.

### ISSUE THREAD

**Issue by christianbrugger** [bitgapp/Cursr#23]
### Describe the Bug/Issue

I have VM Ware on monitor 1, maximized. The mouse is captured and I drag the mouse outside of the VM Ware window to monitor 2. Up to here everything works. Then as soon as I make a left-click the mouse jumps by 20% across the screen. The first screen has 100% zoom, the second 200%, a 1to1 ratio is applied between their border.

### Your Environment
 - Windows 10, 64 bit
 - Cursr Version 1.4.8

**Comment by ragauskl** [comment]
That's odd, Cursr doesn't do anything on mouse clicks

I'll look into the issue and if possible (if not limited by Windows provided functionality - which shouldn't be the case but not impossible) release a fix with next update on which I'm working at the moment

**Comment by christianbrugger** [comment]
This sounds great. Thank you. Let me know if you need more help reproducing the bug.

Greetings

**Comment by ragauskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [VMWare git issue](https://trello.com/c/KrMB0Hb0/154-vmware-git-issue)

**Comment by ragauskl** [comment]
@christianbrugger Apologies for taking a while to resolve this issue, I've added temporary fix to v1.4.11 which I'll release in upcoming days, the mouse should no longer jump around, if issue still persists constantly after v1.4.11 let me know (if you're still using Cursr), the solution is not 100% fail proof, I'll be looking into this issue more for v1.5+ release and I'll also see if I can make Cursr work even when VMWare is capturing the mouse

**Comment by christianbrugger** [comment]
These are great news. Yes I am still using Cursr. Looking forward to the release.
