### ISSUE TITLE
Auto-disable not working for some games

### ISSUE THREAD

**Issue by ragauskl** [bitgapp/Cursr#25]
Seems like Cursr auto-disable feature is not working with some games like:

"Halo infinite, Halo MCC, Fallout 4, Final Fantasy xii/xii-2, Skyrim Special edition, Scarlet Nexus, Tales of Arise. none of them would auto disable in either exclusive full screen or borderless."
![image](https://user-images.githubusercontent.com/113640095/193128997-2ac2a6a6-8363-43c8-ae82-231a3fe5ad81.png)

_Originally posted by @SirBildigan in https://github.com/bitgapp/Cursr/issues/24#issuecomment-1262744413_

**Comment by ragauskl** [comment]
Minor changes and additional logging included in v1.4.11, however I could not replicate the issue when testing with list of games including League of Legends and Halo Infinite, Cursr auto disables as expected

Will keep this issue open for couple months in case anyone will have it and will be able to provide debug logs

**Comment by SirBildigan** [comment]
I was able to get some of the games to work recently, guess it helps to restart cursr after adding the games to the list or it wont use them.

**Comment by Richie81** [comment]
It's not necessarily because of the games. I had the same issue with Witcher 3. Turned on the debug mode, monitored the logs and saw that there's the Microsoft Xbox Game Bar running in the background and detected as a full screen app. Somehow it didn't recognize Witcher 3 as being full screen and active until I disabled the Xbox Game Bar.

Here's a small guide on how to disable it:
https://www.groovypost.com/howto/disable-xbox-game-bar-on-windows/

**Comment by ragauskl** [comment]
@Richie81 I'll have a look at this and see if I can replicate this and add a solution for it in Cursr so that no action is needed on user side, thank you for looking into the logs and debugging it as well! 

Maybe the Xbox Game Bar prevents the game from being full size of the screen by 1px or so in some cases, for simplicity's sake Cursr only checks if process fills full size of the screen so if it's 1px short it wont detect it. There is list of other ways to check it but they vary a lot (inconsistent) based on implementation of the software or game, so I left that out for time being to see how just detection by size works out

**Comment by ragauskl** [comment]
I've added some changes in  previous 1.6.2 where issue was replicated when 'top-most' windows and overlays are present. I'll keep this issue open for another month, but if there will be no more activity I'll close it as done
