### ISSUE TITLE
Failed to retrive information on displays

### ISSUE THREAD

**Issue by udomoody** [bitgapp/Cursr#31]
### Describe the Bug/Issue
Since updating to version 1.4.12 I always get the issue "Failed to retrieve information on 4 displays". No Displays are recognized in Cursr.

### Steps to Reproduce

Update to 1.4.12 and restart

### Your Environment
 - OS details:  Windows 10 x64
 - Cursr Version: 1.4.12
 - License: Free

**Comment by JoryHogeveen** [comment]
Same issue here

**Comment by e30Birdy** [comment]
Got the same today, hadnt noticed it but I was looking up a keybind and saw it

**Comment by ragauskl** [comment]
Working on the issue, will get a fix out asap, in 1.4.12 I've added some changes because another user had an issue where one of displays was not loading, but I did not receive logs so it was a guess fix, looks like that causes current issue.

**Comment by ragauskl** [comment]
In meantime you can downgrade back to v1.4.11 from releases [list](https://github.com/bitgapp/Cursr/releases/tag/v1.4.11):

* Windows - [Install-Cursr.exe](https://github.com/bitgapp/Cursr/releases/download/v1.4.11/Install-Cursr.exe)

**Comment by e30Birdy** [comment]
> In meantime you can downgrade back to v1.4.11 from releases [list](https://github.com/bitgapp/Cursr/releases/tag/v1.4.11):
> 
> * Windows - [Install-Cursr.exe](https://github.com/bitgapp/Cursr/releases/download/v1.4.11/Install-Cursr.exe)

If you need a log to see the issue let me know per email.

**Comment by ragauskl** [comment]
I've made a prebuild that should resolve the issue, whenever someone will have time could I ask you to download the [v1.4.13-prerelease](https://wormhole.app/Y20KB#FM2gpmvy8APIDJIalLW_rA) and see if that fixed the problem? to make sure it's fixed before I make it a public release

In hopefully unlikely case where problem still persists I'll need to ask you to enable Debug mode in settings, restart Cursr so issue happens again and then next to Debug mode there's a button that will open app.log file location, which will need to be forwarded to contact@cursr.app

**Comment by e30Birdy** [comment]
> I've made a prebuild that should resolve the issue, whenever someone will have time could I ask you to download the [v1.4.13-prerelease](https://wormhole.app/Y20KB#FM2gpmvy8APIDJIalLW_rA) and see if that fixed the problem? to make sure it's fixed before I make it a public release
> 
> In hopefully unlikely case where problem still persists I'll need to ask you to enable Debug mode in settings, restart Cursr so issue happens again and then next to Debug mode there's a button that will open app.log file location, which will need to be forwarded to [contact@cursr.app](mailto:contact@cursr.app)

Works great with fix!

**Comment by ragauskl** [comment]
closing issue as update v1.4.13 with the fix is now released
