### ISSUE TITLE
Cursr compatibility with Quake Champions

### ISSUE THREAD

**Issue by sirinsidiator** [bitgapp/Cursr#32]
### Describe the Bug/Issue
Cursr is currently not compatible with Quake Champions. When I move the mouse the frame rate drops towards 0, which makes the game completely unplayable.

### Steps to Reproduce

1. Activate the In-Game FPS counter in the steam settings
2. Start Quake Champions
3. Move the mouse in the main menu and watch the FPS drop (no need to actually join a game for testing)

Disabling the Mouse Transitions in Cursr makes no difference. I have to completely close the program for QC to work properly.

### Expected Behavior

Cursr should not have any noticeable performance impact on QC (and potentially other games) whatsoever.

### Your Environment
 - OS details: Windows 11 22H2
 - Cursr Version: 1.4.12 and 1.4.13
 - License: Free
 - GPU: AMD Radeon RX 6800 XT (in case that makes a difference)

### Additional Context
Googling for QC performance issues gave lots of results for people having similar problems, so I tried all those solutions to no avail. When I saw that there is a new version of Cursr I remembered that I have that running and tried to close it on a hunch. Turned out that was the solution all along.
Quake Champions is free to play and can be downloaded on Steam: https://store.steampowered.com/app/611500/Quake_Champions/

**Comment by sirinsidiator** [comment]
No worries. I don't play QC on a regular basis and I can just close Cursr while I play.

I'm using an AMD Ryzen 5900X. When I start a match without Cursr the usage is at around 25% regardless of mouse movement:
![image](https://user-images.githubusercontent.com/10908027/210638129-13111ef5-26f8-4d7d-9e7a-577ef8c4ce60.png)

With Cursr it's marginally higher while I move the mouse around. The last 20 seconds I stood still and it went down by a couple percent:
![image](https://user-images.githubusercontent.com/10908027/210638775-9cec94f0-77e7-47ce-a785-635d89cf7f67.png)

The individual cores also do not show more than 45% usage.

**Comment by ragauskl** [comment]
@sirinsidiator There was another use with similar issue on Cursr v1.4.x, I haven't included a targeted fix, but seems like one of the changes in Beta have resolved the issue for the other user. You could try downloading the latest Beta v1.5.x and see if that improves anything on your end. Beta can be downloaded from the official website, just scroll down a bit and you will see it. It says 'Beta' but it's 'Beta' for KVM users/multiple device connection, for previous functionality it should be stable and improved.

**Comment by sirinsidiator** [comment]
Sorry for the late reply. I just gave it a try and it seems to be fixed in the beta. I also tested it with the old version and that one is still lagging, so it seems to be indeed something in the new build that fixes it.
