### ISSUE TITLE
Feature Request: Hide Icon from Status Bar

### ISSUE THREAD

**Issue by orenyomtov** [bitgapp/Cursr#33]
### Describe the Issue
I have limited space in my Mac's status bar, and I'd like to be able to hide Cursr's icon using a configuration option

**Comment by ragauskl** [comment]
I'll look into adding this in future,currently I'm working on a big feature, after that will probably need to do some additional stability and bug fixing, but then should have more time on my hands to add this as an option

**Comment by ianjukes** [comment]
I'd also like the option for a monochrome (non-color) icon too. Cursr is the only icon in my menu bar that is colorful! 😊

**Comment by ragauskl** [comment]
@ianjukes Monochrome tray icon is now available in v1.5.0 Beta if you're interested, I've created separate issue for this https://github.com/bitgapp/Cursr/issues/38 that will have info on where to change it, same as I mentioned in other issue you created - it will be released with stable v1.5.0 on or before 8th of May

**Comment by ragauskl** [comment]
@ianjukes  Monochrome option is now available in live v1.5.0, you will find it under 'Settings > General > Theme', I suggest choosing 'system' color, only manually select light or dark if system is not working for any reason or does not look well with current custom theme

@orenyomtov Will be looking into hiding status bar for the next update

**Comment by ragauskl** [comment]
@orenyomtov  As of v1.6.0 option to hide the icon from status bar is now available in Settings > General > Theme
