### ISSUE TITLE
Feature Request: Block screen edges from allowing mouse to pass through

### ISSUE THREAD

**Issue by ianjukes** [bitgapp/Cursr#34]
I have a requirement to actually _stop_ the mouse from moving through to another monitor and wish to select the edge/custom ratio and then block the mouse from moving through on that edge/custom ratio.

I hope that makes sense!

**Comment by ianjukes** [comment]
Just to add to this – it would also be helpful to allow the mouse to pass through in one direction, but not back in the other.

**Comment by ragauskl** [comment]
Both functionalities are already planned/in the backlog and will be coming out in near future, I just need to finish v1.5.0 and after it's out you'll likely see option to block screen edges in one/both directions in v1.5.1 - v1.5.3

**Comment by ianjukes** [comment]
Thats amazing @ragauskl – I look forward to the update. Thank you.

**Comment by ianjukes** [comment]
Hi @ragauskl -- do you have any update on the schedule for next update?

**Comment by ragauskl** [comment]
Hey @ianjukes, for the mentioned feature it will either be before 8 May or after ~10 June. I already released  v.1.5.0 in Beta and currently I'm dealing with some core issues and bugs, I won't have time to do a patch update in meantime but I'm adding all fixes and features to v1.5.0 as I've set myself a cut off date of 8 May to make a stable release for 1.5.0.

If there won't be any more serious issues with the Beta I will be able to include this feature in one of the updates for v1.5.0 (Beta version can be downloaded from cursr.app, auto-updates will work as usual) or you can wait for the stable release. However if there will be more issues I might not have time to include it before 8 May and until 10 Jun I'll have limited availability to work, so in that case the feature would come out after 10 June

**Comment by ianjukes** [comment]
@ragauskl That's great. No pressure! Just was hoping for some data visibility. App is working really well for me so far.

**Comment by ragauskl** [comment]
@ianjukes Just wanted to leave an update on the timeline, I've just released v1.6.0 and will be looking into including this feature in v1.7.0, hard to say for sure but probably in aprox 2 months time as in between I might need to do patch updates and need to start working on Cursr marketing at same time

**Comment by ragauskl** [comment]
Just a quick update - 1.7 is now available in pre-release but I haven't added this feature, however I'm still thinking to add it before making 1.7 a stable release.

**Comment by ragauskl** [comment]
Feature now added and will be in 1.7 stable release. It is not perfect however as visually you'll be able to see mouse moving past border especially if you try to do so on purpose, but once you stop moving the mouse it will be where you expect it to be - at the edge that 'blocks' it from going over.

I will be looking into better solution, but it will be a complicated one potentially requiring a custom driver with which I have no experience working with yet, so it may be some time until I figure it out and implement it into Cursr.

**Comment by ragauskl** [comment]
Feature now available in stable release 1.7, if no further comments are made on the issue in next 2-3 week I'll close it as complete

**Comment by ianjukes** [comment]
Hi @ragauskl! I've just updated (been crazy busy with work) but can't figure out how to use the blocking feature?? Any advice - or documentation?
