### ISSUE TITLE
Feature Request: Quick Jump shortcut

### ISSUE THREAD

**Issue by Dworf** [bitgapp/Cursr#36]
Im testing and playing with version v1.5.0-beta.1:

would love to see quick jump shortcut where you press shortcut for example "alt + ~" and on all monitors you get numbers from 1-9 or from A-Z and you just press 5 to jump with mouse to that monitor.

**Comment by ragauskl** [comment]
1.7 is now available in pre-release mode, to allow update to pre-release you'll need to enable 'Early Access' mode in 'General' settings and 'check for updates' in 'About' settings section.

Alternatively you can wait for 1.7 to be released in stable mode as soon as some users test it and I make sure it's stable.

While it does not contain exact solution mentioned - you can now use keyboard shortcuts to move mouse to set location and where multiple layouts are used - you can bind specific shortcuts to only be used when a setup is selected. You can also set up keyboard shortcut to quickly open up pre-filled 'new move-to shortcut' form based on current location of the mouse, making them easier to set-up.

I did want to add shortcuts for quick movement to display 1-9 or A-Z , and still might do so, I just haven't settled on what would be the best user experience when this is used in KVM. As Cursr has KVM functionality I need to make shortcuts work with and without it making it a bit more difficult in terms of user experience.

**Comment by ragauskl** [comment]
@Dworf If you're still interested in the feature, I've had an idea that so far seems best to me and wanted to know your thoughts:

From linked issue #60 :

> Just now I thought that shortcut + arrow keys (or custom defined like WASD) can be used to move mouse to display above/bellow/left/right of where mouse currently is. Cursr cannot know the position of displays but users can already drag and drop displays to represent their real life display layout/setup and Cursr could use that as 'source of truth' for the directional mouse jump to next display

**Comment by ragauskl** [comment]
closing due to update available and no further activity
