### ISSUE TITLE
Invert Trackpad - Feature Request

### ISSUE THREAD

**Issue by computesam** [bitgapp/Cursr#39]
# 💡Request for Invert Mouse Scroll
### Users need the ability to invert scroll from a Laptop trackpad when active on onother screen.

- Allow users to select which screens have invert scroll
- Run this option/ setting through Curse and NOT the OS, this will keep things running mindfully if disconnected, etc.

**Comment by ragauskl** [comment]
Not a problem, I initially fixed the scrolling for KVM 1.5.0 but the when I tried setup with different devices I found that scrolling still seemed to be incorrectly inverted depending on devices connected. So I'll be adding a fix for it in next update, I can look into adding setting in user interface too

**Comment by computesam** [comment]
@ragauskl Awesome work, great job keeping up with the community!

I look forward to this Feature/Fix soon!

**Comment by ragauskl** [comment]
@computesam I've released update 1.5.0-beta.4 with the fix, let me know if it now works like you expect it too or if you would still like to see a separate setting in Cursr for selecting invert scroll

**Comment by computesam** [comment]
@ragauskl  I can confirm that it works like a charm! You have no idea the excitement I had on my face when I saw the update popup! Great work! Please feel free to close the thread!

**Comment by ragauskl** [comment]
@computesam as this thread was opened primarily due to existing bug and it was solved I'm closing this issue, however I opened another one specifically for the feature #42  so people can upvote it to increase it's priority
