### ISSUE TITLE
Clipboard Manager

### ISSUE THREAD

**Issue by FailureSam** [bitgapp/Cursr#43]
# Clipboard Manager
Users need the ability to copy paste text from one PC to another with basic platform support.
This is one big thing I miss from Synergy.

## Features
Ability to see previous copied text (and possibly images?)
This would make me and many users VERY happy :)

Thanks for the great work!

**Comment by ragauskl** [comment]
@computesam Clipboard Manager will be definitely added in near future 👍  it's on the top of the list of to-do things for Cursr KVM, I simply did not have the time to add it yet while I was making sure the base of the KVM functionality is stable

I'm currently on long overdue holiday, but I'm still getting some work done just in smaller amounts and prioritising any critical issues for the time being. At some point after 10th of June I'll be back working full time on Cursr. In meantime I'm trying to get more people testing the KVM Beta to catch as many issues as possible. 

If you check KVM Beta release notes in app 'Settings > About > Release Notes' you'll find more listed upcoming bug fixes and features (Clipboard included), there are also more things that I'm already planning that are not listed in Release Notes yet

Rest assured Cursr KVM is and will remain focused on making using multiple devices as seamlessly as possible

**Comment by ragauskl** [comment]
@FailureSam stable release v1.5.0 is now live and it includes clipboard sharing for image, text, rich format text and html, gif's currently are not supported and will only copy first frame of the gif as an image. More formats will be coming out in future, also increase in clipboard size will also be coming, in most cases current limit should not be an issue, unless you're copying large image.

If there's specific format you'd like to see, feel free to open new issue and I'll see when I can include it into Cursr 👍
