### ISSUE TITLE
Dragging a window Question

### ISSUE THREAD

**Issue by Savant-sys** [bitgapp/Cursr#45]
### Description
Dragging a window that can keep the cursor slightly stuck at the edge of the screen in order to maximize it instead of going to the other monitor very smoothly. Can Cursr detect that I'm dragging a window in order to make the cursor get slightly blocked by the edge of the screen? Is there a way to change some settings for that? Thanks!

**Comment by ragauskl** [comment]
@Savant-sys I've finally released Cursr 1.5.0 as a stable release and will be looking into this feature for next update

**Comment by ragauskl** [comment]
@Savant-sys With v1.6.0 release Cursr now has 2 options that help to deal with the issue where borders are linked by Cursr (borders joined natively by OS will not be affected):

* A keyboard shortcut which you can set in settings. Once set key(s) are pressed and held Cursr will allow (if by default disabled) or disallow (if by default enabled) mouse transitions through custom links. So you could set it to 'Alt' and when dragging a window, if you want to snap it to edge, hold Alt and mouse won't move over custom Cursr borders
* Set mouse speed in settings, if mouse is moved at set speed or lower it will not move over custom Cursr borders. So when dragging a window, if you drag it quickly - you can move it to another display, but if you move it slowly bellow the threshold it will stay within the same display and allow you to snap it to the edge. This also allows to move slowly to border and if you change your mind or did not move the mouse fast enough you can 'push through' the border if you move the mouse at faster speed
