### ISSUE TITLE
cannot sign in.

### ISSUE THREAD

**Issue by roberthuang0306** [bitgapp/Cursr#46]
### Describe the Bug/Issue

trying to purchase, but failed to sign in
### Steps to Reproduce

Go to https://cursr.app/login, enter email, and click sign in.
an error message pops up: "Failed to send email. Internal server error."
### Expected Behavior

**Screenshots**
![Screenshot 2023-10-21 at 9 19 51 PM](https://github.com/bitgapp/Cursr/assets/47892279/a6f8a8e5-14de-4366-abc6-e1cf31b90c62)

### Your Environment
 - OS details: [e.g. Windows 10 x64]
 - Cursr Version: [e.g. 1.0.0]
 - License: [e.g. Pro/Free] (Important in some cases because Pro has a different internal state compared to Free version)
Mac 14.1
Safari

**Comment by ragauskl** [comment]
I'll have a look at this first thing in the morning and let you know when it's fixed (if same day) or update on when to expect a fix

**Comment by ragauskl** [comment]
@roberthuang0306  The issue has now been fixed
