### ISSUE TITLE
Missing keys

### ISSUE THREAD

**Issue by cuestaluis** [bitgapp/Cursr#52]
When switching from PC to Mac some keys on the keyboard stop working or cause unexpected results. The most affected keys are E, D, F, and M, and also Alt/Optn, Ctrl, etc.

Also special characters which are compound keystrokes don't work and remove focus from the app where I'm typing, for example: ' + e = é 

I have tried this with both keyboard layouts (Current and Source)

Also the side keys on my mouse are not mapped to anything.

Everything works on the windows machine as expected.

### Steps to Reproduce

1. Transition to the Mac from Windows.
2. Try to write on any text field or use a shortcut.

### Expected Behavior

When switching computers, the keyboard should work the same as in the host machine.

### Your Environment
 - OS details: Windows 11 Home 22631.3007 and MacOS 14.2.1 (23C71)
 - Cursr Version: 1.6.6
 - License: Free

### Additional Context

Keyboard and mouse are both wired to a hub on the Windows PC, the keyaboard layout is ISO US, and the mouse is a Razer Basilisk V3, and the keyboard is an Akko 3108 V2

**Comment by ragauskl** [comment]
When this happens you need to press 'Fn' on keyboard connected to Mac. This is a known issue and I've been trying to fix this for some time, I believe currently it happens after arrow keys are used. 

What happens is when some keys are simulated on Mac, Mac itself sets 'Fn' key to 'down' and never releases it basically locking it, as Fn key cannot be simulated easily you'll need to manually press it to cause 'release' of Fn button.

I've added Fn state checks, first for keys that can trigger it, then for all keys but this still happens. I will be adding a fix for this in upcoming version 1.7

**Comment by ragauskl** [comment]
1.7 is now available in pre-release mode, to allow update to pre-release you'll need to enable 'Early Access' mode in 'General' settings and 'check for updates' in 'About' settings section.

Alternatively you can wait for 1.7 to be released in stable mode as soon as some users test it and I make sure it's stable.

**Comment by ragauskl** [comment]
Fix now available in stable release 1.7, if no further comments are made on the issue in next 2-3 week I'll close it as complete
