### ISSUE TITLE
Extended license deemed incompatible

### ISSUE THREAD

**Issue by Immateria** [bitgapp/Cursr#61]
My original (perpetual)licensing period had expired before the new 1.7.0-prerelease, so I purchased the year extension.
I cannot seem to get the application to accept my license by the account page link, or the downloaded license file. I have refreshed the license on the account page, and it says the most recent version. I have waited just under a day to see if it was a server licensing issue.

### Expected Behavior
Acceptance of valid license

![image](https://github.com/bitgapp/Cursr/assets/24444634/ccea1b1c-5e18-4183-8a6d-160110229231)
<img width="1880" alt="image" src="https://github.com/bitgapp/Cursr/assets/24444634/5b4fa34a-b827-4f50-a6ec-e785b58860a3">

### Your Environment
 - OS details: macOS 13.6.5, Intel MacBook Pro 2019
 - Cursr Version: 1.7.0-prerelease
 - License: Pro - Perpetual

**Comment by ragauskl** [comment]
You probably did but just to make sure - Did you ensure you downloaded and applied the refreshed license and did not try to apply the one you already had in file system/old one?

You can also try to go to account, sign in within the app and then press 'Refresh/reload' in-app - it will pull the license in by itself based on machine ID and your account

If that still does not work, let me know

**Comment by Immateria** [comment]
I tried both of those things multiple times, and it would still give me the above message. But, complain about something and it gets fixed. It resolved itself somehow, and I have no idea why, as I didn't do anything new.
So, while this is fixed for me currently, I wonder if there's some underlying issue that still needs to be resolved.

Also, I appreciate the swift response.

**Comment by ragauskl** [comment]
I'm glad it's resolved now, I'll close this issue then but will look into this before next release.

 The only possible cause I can think of is if app for any reason used stored license instead of the new one as new one can't possibly have information about version 1.5 if it's renewed to 1.7. So I'll make sure this doesn't happen with further releases
