### ISSUE TITLE
Mouse moves to wrong monitor when moving quickly

### ISSUE THREAD

**Issue by turcottep** [bitgapp/Cursr#62]
### Describe the Bug/Issue

This is my monitor setup:
<img width="760" alt="cursr_bug" src="https://github.com/bitgapp/Cursr/assets/32850285/c4f247ba-4ad7-4076-bf6c-a3216e98299b">

Starting from the top right corner of the bottom screen, when I move the mouse slowly in a diagonal to the top right, it ends up in the screen on the right, but if I do it quickly, it ends up in the bottom left of the top screen.

Here is a video showing it:

https://github.com/bitgapp/Cursr/assets/32850285/7b0db2d3-fe25-4346-89d7-75da97b44a8e

### Steps to Reproduce

Not sure how you'll be able to reproduce it without having the same monitor setup, but the bugs happens every time I move over a certain speed.

### Expected Behavior

See above

### Your Environment
 
 OS details: 
   macOS Ventura 13.5.1
   Apple M1 Max

Displays: 
  Built-in Liquid Retina XDR Display : 16-inch(3456 x 2234) (scaled to 1728x1117)
  LG ULTRAFINE Display: 32-Inch (3840-2160) (scaled to 1440x2560)
  LG ULTRAFINE Display: 32-Inch (3840-2160) (scaled to 1440x2560)
  LG ULTRAFINE Display: 32-Inch (3840-2160) (scaled to 1440x2560)

Cursr Version: 1.6.6
License:  Pro

**Comment by ragauskl** [comment]
If this is an issue that I think it is I should be able to replicate it with the displays I have. I'll release a fix (if I can replicate it) or if I can't replicate it, a improvement in Cursr edge detection with version 1.7 stable or first patch 1.7.1 soon after the stable release

**Comment by turcottep** [comment]
thanks a lot! great product otherwise

**Comment by ragauskl** [comment]
I've been trying to replicate the issue but had not luck. Could I ask you to enable Debug mode in settings, replicate the issue and send me the compressed logs (you'll find a button next to debug mode for that) to contact@cursr.app?

**Comment by ragauskl** [comment]
Fix now available in stable release 1.7, if no further comments are made on the issue in next 2-3 week I'll close it as complete

**Comment by turcottep** [comment]
I updated and it seems to work perfectly, thanks a lot!
