### ISSUE TITLE
Extend clipboard sharing feature to include images

### ISSUE THREAD

**Issue by anthonypants** [bitgapp/Cursr#65]
### Describe the Issue
I would like for the ability to copy and paste images across computers via clipboard sharing.

### Additional context
Similar to copying text and sharing it across computers, if I put an image onto my clipboard, I should be able to share that across other computers, too.

**Comment by ragauskl** [comment]
Cursr already supports basic image types in clipboard. If this feature is not working for you there's either a bug with Cursr or the place you're trying to copy the image from provides it in currently unsupported format (which should be easy to add, I just didn't have the time to go over all formats yet and started from basics)

Can you:
1. Try copy pasting any image from Google images from one device to another.
2. If first stip did not work - it's likely a bug, if it did work try pasting the image you had issue with to https://evercoder.github.io/clipboard-inspector/ and attach screenshot of what you see, this will help me identify missing format

**Comment by anthonypants** [comment]
1. Copying an image from Google images (Firefox, Windows) pasted successfully into the Clipboard inspector (Safari, macOS)
2. Taking a screenshot of a window in Windows pasted successfully into the Clipboard Inspector (Safari, macOS)
3. Copying an image from the Photos app in Windows did not appear to update the clipboard in macOS, and pasting into Clipboard Inspector just re-pastes the last thing in the macOS clipboard.
4. Copying an image from Google images (Safari, macOS) and pasting into Clipboard Inspector (Firefox, Windows) will re-paste the last thing in the Windows clipboard. If I manually clear out the clipboard in Windows, then copy some image from macOS, pasting into Clipboard Inspector (Safari, macOS) produces the following result:
![image](https://github.com/bitgapp/Cursr/assets/6431630/c1ddd899-4b63-409d-a734-d53c73be8e44)
I don't really think that's very helpful, but if there's a debug mode I can turn on in Cursr, I'd be happy to give that a shot.

Also, with Cursr up and running, I'm able to copy and paste locally without issue. So, copying an image from anywhere on either operating system, and then pasting into Clipboard Inspector on the same machine, works fine. Copying and pasting text between computers is also fine.

**Comment by ragauskl** [comment]
Thank you for the detailed information, I'll try replicating this and see if I can include a fix with next couple patches, in any case I'll provide an update on when a fix can be expected

**Comment by ragauskl** [comment]
This should be now fixed in v1.7.2
