### ISSUE TITLE
Cursr Preventing Sleep on Mac

### ISSUE THREAD

**Issue by rchybicki** [bitgapp/Cursr#70]
### Describe the Bug/Issue
Hello,
I'm debugging why my mac won't go to sleep, and the last app that is showing up for me as "Preventing Sleep" in activity monitor, is cursr:
<img width="777" alt="image" src="https://github.com/user-attachments/assets/bd06f267-7d5c-4f38-80cb-83d63901bfee">

### Steps to Reproduce

1. Run cursr
2. Open activity monitor on mac, select the energy tab, sort by "Preventing Sleep"

### Your Environment
 - OS details: Mac Sonoma 14.5
 - Cursr Version: 1.7.2
 - License: Free version

**Comment by ragauskl** [comment]
Are you using Cursr for single device or in KVM mode? When KVM is in use Cursr will trigger sleep prevention but in single device mode it shouldn't be doing that maybe indicating a bug that I need to look into

**Comment by rchybicki** [comment]
Yes, I'm using single device.

**Comment by ragauskl** [comment]
Okay, I'll have a look into what could be causing this

**Comment by ragauskl** [comment]
@rchybicki I checked and tested again, the sleep prevention actually kicks in in single device mode as well, however after 1min of no input activity (like mouse move, click or keyboard input) it gets disabled. For stable release of 1.7.3 I'll completely remove this while KVM is inactive. However if you would open activity monitor and don't use the device for 1min or so (maybe 2 to give time for activity monitor to update) it should show that Cursr is not preventing sleep anymore. So likely it wasn't Cursr that was causing overall sleep of the device

**Comment by rchybicki** [comment]
Hey @ragauskl, thanks for checking that out. I didn't think to wait when I was doing my testing, but it does indeed drop the "preventing sleep" after a minute, I disabled Cursr for no reason - no issue here.
