### ISSUE TITLE
Connection Setup Terminated

### ISSUE THREAD

**Issue by Wallby** [bitgapp/Cursr#71]
### Describe the Bug/Issue

On one computer the following message appears..
```
Connection Setup Terminated
Timed out waiting for connection to <GUID> to get registered
```
\<GUID\> here is some valid looking GUID.

Then after a bit longer (always later) this message appears on the other computer..
```
Connection Setup Terminated
Election failed: Peers failed to vote on cluster leader
```

### Steps to Reproduce

1. Open Cursr on two devices (I am using one laptop and one desktop) both running Windows 10
2. On both machines click this button.. ![image](https://github.com/user-attachments/assets/ff90c654-daf2-417f-96c4-30dc3ee88935)
3. Wait till the above problems occur

### Expected Behavior
\-

**Screenshots**
\-

### Your Environment
 - OS details: Windows 10 x64
 - Cursr Version: 1.7.2
 - License: Free

### Additional Context
\-

**Comment by Wallby** [comment]
Fixed it already. One of the computers was recently reset thus the wifi network wasn't set as private yet.

**Comment by ragauskl** [comment]
Closing as it's solved, one note - you only need to click the button on one of the devices, it doesn't hurt to do it on both, but it's not necessary, all it does is 'queries' the network and starts the connection process in all other Cursr instances (where on same discovery port) on network
