### ISSUE TITLE
MacOS - Identical Monitors issues

### ISSUE THREAD

**Issue by sleepinglion251** [bitgapp/Cursr#8]
I am using two monitors that are identical to each other. When I do so, I have noticed that whenever I try to select an edge on one of them, it is mapping to the other monitor. Below, any time I try to map an edge on the left vertical monitor, it always maps it to the same edge on the right vertical monitor. When I selected the edge I have circled below to map to the other green edge, it mapped it to the far right edge of the right monitor.
![Screen Shot 2021-08-07 at 12 59 12 PM](https://user-images.githubusercontent.com/66454074/128609815-491fd66e-e67d-428a-9493-3db5ed446017.png)

**Comment by ragauskl** [comment]
I might have a clue why it's happening, could I ask you to send me conf.json (should be located under 'C:\Users\\\_user_\AppData\Roaming\cursr' if you haven't changed folder location during installation) to email contact@cursr.app or you can paste it in here, just remove your `clientId` from the file

**Comment by ragauskl** [comment]
@sleepinglion251 v1.3.2 is out now with updated display identification, that should resolve the issue.

Could you let me know if the issue has been resolved after update?

**Comment by ragauskl** [comment]
@sleepinglion251 As there have been no further comments on the issue after the fix, I assume it's solved, I'll keep the issue open for couple more days and will close it if there won't be any new comments on the issue by then

**Comment by sleepinglion251** [comment]
I ended up changing my setup to an M1 and can't run that many monitors anymore so I don't have a way to test this anymore. Sorry.

**Comment by ragauskl** [comment]
@sleepinglion251  Understood, I'll close this issue then.

Do you still use Cursr? There's a potential issue with M1, but without M1 I can't test it, I was hoping someone will eventually use Cursr on it, in case you still use Cursr or if it's not working and you'd use it if it was to be fixed on M1, I could release almost ready v1.3.4  which has logs to debug the issue, I would ask for logs after using v1.3.4
