### ISSUE TITLE
Allow half or partial frame mapping

### ISSUE THREAD

**Issue by JoelRSimpson** [bitgapp/Cursr#86]
### Describe the Issue
When you have uneven sized screens or orientations and want them to line up, it isn't possible to split half of a border so that the top half goes to one screen and the bottom half goes to another.  

### Additional context
For example, I have 2 landscape display stacked next to two portrait displays and would like to be able to create the red and blue linkages.
![cursr proposed split border feature](https://github.com/user-attachments/assets/33253e91-11f1-4684-8369-aca955852a39)

**Comment by ragauskl** [comment]
You can do that, but it is a Pro/paid feature (you didn't mention if you have Pro so I'm mentioning just in  case). More info on how to do this can be found in https://cursr.app/docs/how-to  3rd section 'Border Segment Splitting (Pro)'

If you have Pro and followed the instructions and still can't achieve this, let me know and I'll see what I can do to help

**Comment by JoelRSimpson** [comment]
Thank you!  sorry for the errant request.
